# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops" do
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "1330a85a994bb0ac3b623ea0cef3f2e981a7378c6d33c70d744d5a62815b433e"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "2bb6be93a93fd82fab87aa38f560f07f73ff3bb90da5b8b4ecf5ae903c36318d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "1ae8c044b7bdd05d9f27cfad0dd49a3d89c701670e5a7c063d9abadcdf8d6711"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "64d5ae8b614adc167c8e7663369a0858933128b6094490a17c5e6cba40ea522a"
    end
  end

  name "loops"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
