# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.0.4" do
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "53625ee423f6c846182c8257326974182e69aa9ef1917144a30e1d299d3e40d2"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "bcf3b48fcab6b618a14c8b8f8138ab614568c87703cc86a934c767b5fe53c9b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "38c54452d5017115ff0320974d3fdfe4452fa341ceefe12cb05841832719ba53"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "8c16c52980ce752fe7392bd6397305fa502020fad4e0f17201852f2bb6496761"
    end
  end

  name "loops@0.0.4"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
