# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.7.0" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "93e270b4dd874aaca65103ca9af4c89b4306b34969db94c8339b9d9ee844ddc9"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ecbf174186a4665c40a4d18e56f4d3e47b0eef7c6c1b0b772b1b2c40e811992a"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18c9cd8dabf05813032804d4718a433269b8c3fea21ae6dbb6f7d7b62feabe8e"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "96f4f2707141c0e8bed8034b85d86a3052f7c6f130aeb5ba31ef3d30f273dc0c"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops@0.7.0"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
