# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.8.0" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "c8eaf610676d6a3e0d8a702e14d9b8ec7119acae4223709e21b2f245a79274fe"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8371b22d2664fce1ee9a7a1e37c0025fff775d245f20a3ec2173fe14e9bf8b06"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a7946f083a6ac62412b647643b014042309eb503dc9cae7d3a1f1543f62fc56d"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ed53abfb4b8d6b530186aabae479a7826fe3f45c5c002d74d72a801b72c7c26d"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops@0.8.0"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
