# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.0.2" do
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "e5818dde120490b23d5c9bf996e33dd78be52ce9ff14eb7e50b5c105eeace196"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "e1c58ba707417e589d92127ec2f9ceadd72e058b13c632693abd0d1b91b9a314"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "5d7dc8f902979dbb8832a9071fc535b45c5d7202a719f9a27b83c064506a3f07"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "136a2501e53b586da9e192956e23029d8ea927dbdfd9ca5df77ea94cf1f9732c"
    end
  end

  name "loops@0.0.2"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
