# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.0.3" do
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "efe4cc98313a7a13f4118c04965f09631718fb5999e40341f54a2db8cba69ee7"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "b83c5c403d37ea767aa946957941ccce04d82ea80870883891dc0d336c0f68a2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "94ed87bfd50f1f37707d4d86ccc269224a7ec2d71644595edfe7c9fb2927d78d"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "71f2f6e93707b5dbbde45f553b8201a96baf5122375a945f0ead6ce825ad9ed2"
    end
  end

  name "loops@0.0.3"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
