# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.6.0" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "f5fa7999bdf2d94e8753e1d9d3abf5146425d185507ed425641ba805d3137242"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8afd8b79564e0c7f6208a02ff6bb6b96ce9e62267871f0c9de6307294d96c4fe"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a677bcb17f033a30937e003a3486219c923bf29c200f3968f6997dfec441093e"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "184a237552260b2361a0445c992cf11c9a7c658324f14e4de51aadf05558a3ce"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops@0.6.0"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
