# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.0.1" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "3792a6439460a17065aa5a19f108a771203347bfac13635cf824932f8e30305d"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "460ea465c1c2dae01356d1106b50f2067ca6aa66525b739ab6fa956e99e076e8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "a3f16cf4a509a1f41a1b8104ac52dc9abd4d7ed2bed83e2a13db7b237b5f2f8d"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "1ed3d2dc3c0d2b1b5d1d2fdbcfd020a0209a2f56cab370ce728bb48f2e8b14c2"
    end
  end

  name "loops@0.0.1"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
