# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.0.5" do
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "fd2546df117d45427737b65dee8eeff40e2c05a8e6262f1290b8c77825f8b744"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "08a1eec0d0c12453dc50ce1ba3f82157288afbbf598a3b2e49303a4eea402e45"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "3a3266a6d00079affa591f49d1eb4beb8b34010239dc79976d0204ec679de704"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "e33a9f4831262c683fd5e063943fc7c8d9d8194a718d84ee8bca1e595cfe12b4"
    end
  end

  name "loops@0.0.5"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
