# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.1.0" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "e9ae50784d4ba822e78eded82fb59cef1305697db8fb9dbc52313e293323fe44"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "7dec4b9b8f10f3864900ae16177933b698c9ba3b0301173499157d607220205e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "581692f4e748c9a16ce500346c7108208f924ad6f9b587d9562013c37cb5c017"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "84e7d2064d10eaafd90ac9557fc9a37531782023ca309743dc56c292f3af5ce3"
    end
  end

  name "loops@0.1.0"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
