# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops" do
  version "0.0.1-rc1"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "51ae0da8beab46ba992268da24b065e8d423038e25f0d49a75f7aff984d190fa"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "11e7a69fa09cc0fa60f963906c17bb59fb4f4c6e06e5ac5c7ec7a3b0e308bbd9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "6297e017ff69c1fbdd391b5c9c63b5575de66e251405d868f85c2e63bb419ae9"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "e2c06ac4e515e0b2a2d253deea00a5151d40e5d47b5be056eb69652f132aa001"
    end
  end

  name "loops"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
