# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.8.1" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "294fc52f1e57737e3d8b3b5d128afd6fc60eaf1eba5b4f85827ee83964b06685"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8903274b41ca1aa82f6b3c760997e1fe0d6b14fbac969726343a02b7f3e66745"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42ae8a6d40a65f3ecb7e963aa6af6e471c947f1460f0b69abdad31e31ea5db3e"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f45c7975d8ee77355fa37a9b115d0d9b393611030bb0b12949632e6a91f03fe8"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops@0.8.1"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
