# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
      sha256 "0e18d8ee147ec3a44f4ec15cd4334f9334218c2fe7e699552f456da3817c935f"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
      sha256 "039a956d609587ba4538f17318ddcbbfcf0165a7720a75423f212406fe573de3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
      sha256 "619e8f61ed159fd6a281ce0dc1c12debcdafa42c509f7990efc8537a5488acfa"
    end
    on_arm do
      url "https://github.com/Loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
      sha256 "fc07cffd8af6ed2a8cba8eba24d8dcb5b83ef30d5b822a24b72df2f0a97fe24f"
    end
  end

  name "loops"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loops"]
    end
  end

  # No zap stanza required

end
