# This file was generated by GoReleaser. DO NOT EDIT.
cask "loops@0.9.0" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "2a2f8cfd2824a9a1039c567b74e4896a5a361867532199ad4ee2e4a0b790074e"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1b84178250dbff0351fc9307b35e889824ce6aee67382bb1c04427463e2f2e7a"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9bda7104cdc3d1a2c43957ee3b5729294464c962453b5932b1871fa278d6ea10"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "80b47241f7f1535ee52cc9603c53af0e68d883cac27399756a2d7077eab4dac2"
      url "https://github.com/loops-so/cli/releases/download/v#{version}/loops_cli_linux_arm64.tar.gz"
    end
  end

  name "loops@0.9.0"
  desc "Official CLI for Loops"
  homepage "https://loops.so"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loops"

  # No zap stanza required

end
